module("luarocks.site_config")
LUAROCKS_PREFIX=[[/opt/neovim-deps]]
LUA_INCDIR=[[/opt/neovim-deps/include/luajit-2.0]]
LUA_LIBDIR=[[/opt/neovim-deps/lib]]
LUA_BINDIR=[[/opt/neovim-deps/bin]]
LUA_INTERPRETER=[[luajit]]
LUAROCKS_SYSCONFDIR=[[/opt/neovim-deps/etc/luarocks]]
LUAROCKS_ROCKS_TREE=[[/opt/neovim-deps]]
LUAROCKS_FORCE_CONFIG=true
LUAROCKS_ROCKS_SUBDIR=[[/lib/luarocks/rocks]]
LUA_DIR_SET=true
LUAROCKS_UNAME_S=[[Linux]]
LUAROCKS_UNAME_M=[[x86_64]]
LUAROCKS_DOWNLOADER=[[wget]]
LUAROCKS_MD5CHECKER=[[md5sum]]
